apply plugin: 'com.android.application'

android {
    namespace 'com.example.localsensorcloud'
    compileSdk 34

    defaultConfig {
        applicationId 'com.example.localsensorcloud'
        minSdk 26
        targetSdk 34
        versionCode 8
        versionName '1.7'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
